<div id="postnl_add_moment">

    <div class="sub-title">
        <h3><?php echo Mage::helper('postnl')->__('Delivery Options'); ?></h3>
    </div>

    <ul class="option-list">
        <li class="location">
            <div class="bkg">
                <div class="bkg">
                    <div class="content">
                        <strong class="location-name overflow-protect"><?php echo Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getStreetFull(); ?></strong>
                    </div>
                </div>
            </div>
        </li>
        <li class="option">
            <div class="bkg">
                <div class="bkg">
                    <div class="content">
                        <span class="option-dd">
                            <strong class="option-day">Wo</strong>
                            <span class="option-date">20-08</span>
                        </span>
                        <span class="option-radio"></span>
                        <span class="option-time">09:00 - 19:00</span>
                        <span class="option-comment">vandaag + &euro;19,95</span>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <ul class="option-list">
        <li class="add-moment">
            <a id="add_moment_link" class="button" ><span><span><?php echo Mage::helper('postnl')->__('Or pick your own delivery moment'); ?></span></span></a>
        </li>
    </ul>
</div>