<div id="postnl_delivery_options">
    
    <div id="initial_loader" style="display:none;" ><?php echo Mage::helper('postnl')->__('Loading...'); ?></div>
    
    <div class="title">
        <h2><?php echo Mage::helper('postnl')->__('Delivery Options'); ?></h2>
    </div>
    <div class="col2-set">
        <div id="postnl_delivery" class="col-1">
            <h3 class="sub-title"><?php echo Mage::helper('postnl')->__('Delivery'); ?></h3>
            <ul class="option-list">
                <li class="location">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <strong class="location-name overflow-protect"><?php echo Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getStreetFull(); ?></strong>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Di</strong>
                                    <span class="option-date">19-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">16:00 - 19:00</span>
                                <span class="option-comment">vandaag + &euro;19,95</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Wo</strong>
                                    <span class="option-date">20-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">09:00 - 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Do</strong>
                                    <span class="option-date">21-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">09:00 - 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option active">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd"></span>
                                <span class="option-radio"></span>
                                <span class="option-time">19:00 - 21:00</span>
                                <span class="option-comment">avond + &euro;3,00</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Vr</strong>
                                    <span class="option-date">22-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">09:00 - 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Za</strong>
                                    <span class="option-date">23-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">09:00 - 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Di</strong>
                                    <span class="option-date">26-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">09:00 - 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div id="postnl_pickup" class="col-2">
            <h3 class="sub-title"><?php echo Mage::helper('postnl')->__('or Pickup'); ?></h3>
            <ul class="option-list">
                <li class="location">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <strong class="location-name overflow-protect">Albert Heijn</strong>
                                <span class="location-type">Postkantoor</span>
                                <a href="#" onclick="return false;" class="location-info">
                                    <span><?php echo Mage::helper('postnl')->__('More Info'); ?></span>
                                </a>
                                <div class="tooltip">
                                    <div class="tooltip-header">
                                        <strong class="location-name">Albert Heijn</strong>
                                        <strong class="location-address">Nieuwe Binnenweg 288 te Rotterdam</strong>
                                    </div>
                                    <hr class="tooltip-divider" />
                                    <div class="tooltip-content">
                                        <table class="business-hours">
                                            <thead>
                                                <tr>
                                                    <th colspan="2"><?php echo Mage::helper('postnl')->__('Business Hours'); ?>:</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <th>Ma</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Di</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Wo</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Do</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Vr</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Za</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Zo</th>
                                                    <td>12:00 - 20:00</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Di</strong>
                                    <span class="option-date">19-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">vanaf 8:30</span>
                                <span class="option-comment">extra vroeg + &euro;3,00</span>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="option-list">
                <li class="location">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <strong class="location-name overflow-protect">Bruna</strong>
                                <span class="location-type">Postkantoor</span>
                                <a href="#" onclick="return false;" class="location-info">
                                    <span><?php echo Mage::helper('postnl')->__('More Info'); ?></span>
                                </a>
                                <div class="tooltip">
                                    <div class="tooltip-header">
                                        <strong class="location-name">Bruna</strong>
                                        <strong class="location-address">Nieuwe Binnenweg 288 te Rotterdam</strong>
                                    </div>
                                    <hr class="tooltip-divider" />
                                    <div class="tooltip-content">
                                        <table class="business-hours">
                                            <thead>
                                                <tr>
                                                    <th colspan="2"><?php echo Mage::helper('postnl')->__('Business Hours'); ?>:</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <th>Ma</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Di</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Wo</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Do</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Vr</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Za</th>
                                                    <td>08:00 - 21:00</td>
                                                </tr>
                                                <tr>
                                                    <th>Zo</th>
                                                    <td>12:00 - 20:00</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Di</strong>
                                    <span class="option-date">20-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">vanaf 16:00</span>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="option-list">
                <li class="location">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <strong class="location-name overflow-protect">Pakket Automaat</strong>
                                <a href="#" onclick="return false;" class="location-info">
                                    <span><?php echo Mage::helper('postnl')->__('More Info'); ?></span>
                                </a>
                            </div>
                            <div class="tooltip">
                                <div class="tooltip-header">
                                    <strong class="location-name">Pakket Automaat</strong>
                                    <strong class="location-address">Nieuwe Binnenweg 288 te Rotterdam</strong>
                                </div>
                                <hr class="tooltip-divider" />
                                <div class="tooltip-content">
                                    <table class="business-hours">
                                        <thead>
                                            <tr>
                                                <th colspan="2"><?php echo Mage::helper('postnl')->__('Business Hours'); ?>:</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th>Ma</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Di</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Wo</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Do</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Vr</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Za</th>
                                                <td>08:00 - 21:00</td>
                                            </tr>
                                            <tr>
                                                <th>Zo</th>
                                                <td>12:00 - 20:00</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="option">
                    <div class="bkg">
                        <div class="bkg">
                            <div class="content">
                                <span class="option-dd">
                                    <strong class="option-day">Wo</strong>
                                    <span class="option-date">20-08</span>
                                </span>
                                <span class="option-radio"></span>
                                <span class="option-time">vanaf 16:00</span>
                                <span class="option-comment">24/7 beschikbaar</span>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="option-list">
                <li class="add-location">
                    <a id="add_location_link" href="#" ><?php echo Mage::helper('postnl')->__('choose a different pickup location'); ?></a>
                </li>
            </ul>
        </div>
    </div>
    
    <?php // echo $this->getChildHtml('postnl.osc.add.location'); ?>
       
</div>