<?php 
$_postCode = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getPostcode();
$_houseNumber = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getStreet(2);
$_extension = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getStreet(3); 
?>
<div id="postnl_add_location">
    <div class="popup-overlay">
        <div class="popup-window">
            <div class="popup-header">
                <h2><?php echo Mage::helper('postnl')->__('Select Post Office'); ?></h2>
                <div class="search-location">
                    <input type="text" class="input-text" name="" value="<?php echo $_postCode . ', ' . $_houseNumber . $_extension ?>" />
                    <button type="button" class="button btn-search"><span><span><?php echo Mage::helper('postnl')->__('Search'); ?></span></span></button>
                    <ul class="location-options">
                        <li>
                            <a href="javascript:void(0);"><?php echo Mage::helper('postnl')->__('early pickup');?></a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="selected"><?php echo Mage::helper('postnl')->__('opened in the evening');?></a>
                        </li>
                    </ul>
                    <div class="error-msg" style="display:none;"><?php echo Mage::helper('postnl')->__('Geen adres gevonden bij de opgegeven combinatie van straatnaam, postcode, huisnr en woonplaats.'); ?></div>
                </div>
                <a href="javascript:void(0);" title="<?php echo Mage::helper('postnl')->__('Close'); ?>" id="close_popup" class="btn-close"><?php echo Mage::helper('postnl')->__('Close'); ?></a>
            </div>
            <div class="popup-map">
                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_maps.jpg'); ?>" alt="" />
            </div>
            <div class="popup-content">
                <h2><?php echo Mage::helper('postnl')->__('Pickup locations found'); ?><span id="locations_loader"><?php echo Mage::helper('postnl')->__('Loading...'); ?></span></h2>
                <div id="scrollbar_container">  
                    <div id="scrollbar_track">
                        <div id="scrollbar_handle"></div>
                    </div>    
                    <ul id="scrollbar_content" class="location-list">
                        <li class="location">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_bruna.png'); ?>" class="location-icon" alt="Bruna" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Bruna</strong>
                                    <span class="location-address">Nieuwe Binnenweg 42, Rotterdam</span>
                                </span>
                                <span class="location-distance">234 m</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                        <li class="location selected">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_ah.png'); ?>" class="location-icon" alt="Albert Heijn" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Albert Heijn</strong>
                                    <span class="location-address">Oudedijk 427, Rotterdam</span>
                                </span>
                                <span class="location-distance">2.1 km</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                        <li class="location">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_ah.png'); ?>" class="location-icon" alt="Albert Heijn" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Albert Heijn</strong>
                                    <span class="location-address">Scheep Timmermanslaan 23, Rotterdam</span>
                                </span>
                                <span class="location-distance">2.1 km</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                        <li class="location">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_bruna.png'); ?>" class="location-icon" alt="Bruna" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Bruna</strong>
                                    <span class="location-address">Nieuwe Binnenweg 42, Rotterdam</span>
                                </span>
                                <span class="location-distance">234 m</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                        <li class="location selected">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_ah.png'); ?>" class="location-icon" alt="Albert Heijn" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Albert Heijn</strong>
                                    <span class="location-address">Oudedijk 427, Rotterdam</span>
                                </span>
                                <span class="location-distance">2.1 km</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                        <li class="location">
                            <div class="content">
                                <img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/deliveryoptions/tmp_ah.png'); ?>" class="location-icon" alt="Albert Heijn" />
                                <span class="overflow-protect">
                                    <strong class="location-name">Albert Heijn</strong>
                                    <span class="location-address">Scheep Timmermanslaan 23, Rotterdam</span>
                                </span>
                                <span class="location-distance">2.1 km</span>
                                <a href="javascript:void(0);" class="location-info"><?php echo Mage::helper('postnl')->__('business hours'); ?></a>
                            </div>
                        </li>
                    </ul>
                </div>
                <script type="text/javascript">
                    var scrollbar = new Control.ScrollBar('scrollbar_content','scrollbar_track');
                </script>
                <div class="location-details">
                    <div class="left">
                        <strong class="location-name">Albert Heijn</strong>
                        <strong class="location-address">Oudedijk 427 te Rotterdam</strong>
                        <span class="location-info">Extra vroeg ophalen mogelijk<br />'s Avonds open</span>
                    </div>
                    <div class="right">
                        <table class="business-hours">
                            <thead>
                                <tr>
                                    <th colspan="2"><?php echo Mage::helper('postnl')->__('Business Hours'); ?>:</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Mo') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Tu') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('We') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Th') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Fr') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Sa') ?></th>
                                    <td>08:00 - 21:00</td>
                                </tr>
                                <tr>
                                    <th><?php echo Mage::helper('postnl')->__('Su') ?></th>
                                    <td>12:00 - 20:00</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <a href="javascript:void(0);" title="<?php echo Mage::helper('postnl')->__('Close'); ?>" class="btn-close"><?php echo Mage::helper('postnl')->__('Close'); ?></a>
                </div>
                <div class="button-set">
                    <button type="button" class="button btn-save next"><span><span><?php echo Mage::helper('postnl')->__('Save'); ?></span></span></button>
                </div>
            </div>
        </div>
    </div>
</div>