<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BarcodeWebService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="BarcodeWebService.xsd" namespace="http://tntpost.nl/parcels/CIF/BarcodeService/"/>
      <xsd:import schemaLocation="BarcodeWebService_1_2.xsd" namespace="http://schemas.datacontract.org/2004/07/Tpp.Cif.WebServices.WebServices"/>
      <xsd:import schemaLocation="BarcodeWebService_1_2_3_4.xsd" namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
      <xsd:import schemaLocation="BarcodeWebService_1.xsd" namespace="http://schemas.datacontract.org/2004/07/Tpp.Cif.Services.Domain.BarcodeService"/>
      <xsd:import schemaLocation="BarcodeWebService_1_2_3.xsd" namespace="http://schemas.datacontract.org/2004/07/Tpp.Cif.Services.Services.Exception"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="GenerateBarcodeRequestContract">
    <wsdl:part name="GenerateBarcode" element="q1:GenerateBarcode" xmlns:q1="http://tntpost.nl/parcels/CIF/BarcodeService/"/>
  </wsdl:message>
  <wsdl:message name="GenerateBarcodeResponseContract">
    <wsdl:part name="GenerateBarcodeResponse" element="q2:GenerateBarcodeResponse" xmlns:q2="http://tntpost.nl/parcels/CIF/BarcodeService/"/>
  </wsdl:message>
  <wsdl:message name="IBarcodeWebService_GenerateBarcode_CifExceptionFault_FaultMessage">
    <wsdl:part name="detail" element="q3:CifException" xmlns:q3="http://schemas.datacontract.org/2004/07/Tpp.Cif.WebServices.WebServices"/>
  </wsdl:message>
  <wsdl:portType name="IBarcodeWebService">
    <wsdl:operation name="GenerateBarcode">
      <wsdl:input wsaw:Action="http://tempuri.org/IBarcodeWebService/GenerateBarcode" name="GenerateBarcodeRequestContract" message="tns:GenerateBarcodeRequestContract"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IBarcodeWebService/GenerateBarcodeResponse" name="GenerateBarcodeResponseContract" message="tns:GenerateBarcodeResponseContract"/>
      <wsdl:fault wsaw:Action="http://tempuri.org/IBarcodeWebService/GenerateBarcodeCifExceptionFault" name="CifExceptionFault" message="tns:IBarcodeWebService_GenerateBarcode_CifExceptionFault_FaultMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IBarcodeWebService" type="tns:IBarcodeWebService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GenerateBarcode">
      <soap:operation soapAction="http://tempuri.org/IBarcodeWebService/GenerateBarcode" style="document"/>
      <wsdl:input name="GenerateBarcodeRequestContract">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GenerateBarcodeResponseContract">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CifExceptionFault">
        <soap:fault name="CifExceptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BarcodeWebService">
    <wsdl:port name="BasicHttpBinding_IBarcodeWebService" binding="tns:BasicHttpBinding_IBarcodeWebService">
      <soap:address location="https://service.postnl.com/CIF/BarcodeWebService/1_0/BarcodeWebService.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>