<?php
/**
 *                  ___________       __            __   
 *                  \__    ___/____ _/  |_ _____   |  |  
 *                    |    |  /  _ \\   __\\__  \  |  |
 *                    |    | |  |_| ||  |   / __ \_|  |__
 *                    |____|  \____/ |__|  (____  /|____/
 *                                              \/       
 *          ___          __                                   __   
 *         |   |  ____ _/  |_   ____ _______   ____    ____ _/  |_ 
 *         |   | /    \\   __\_/ __ \\_  __ \ /    \ _/ __ \\   __\
 *         |   ||   |  \|  |  \  ___/ |  | \/|   |  \\  ___/ |  |  
 *         |___||___|  /|__|   \_____>|__|   |___|  / \_____>|__|  
 *                  \/                           \/               
 *                  ________       
 *                 /  _____/_______   ____   __ __ ______  
 *                /   \  ___\_  __ \ /  _ \ |  |  \\____ \ 
 *                \    \_\  \|  | \/|  |_| ||  |  /|  |_| |
 *                 \______  /|__|    \____/ |____/ |   __/ 
 *                        \/                       |__|    
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL: 
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@totalinternetgroup.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@totalinternetgroup.nl for more information.
 *
 * @copyright   Copyright (c) 2013 Total Internet Group B.V. (http://www.totalinternetgroup.nl)
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */	
?>
<?php $_quote             = $this->getQuote(); ?>
<?php $_order             = $this->getPostnlOrder(); ?>
<?php $_itemCollection    = $this->getItems(); ?>
<?php $_billingAddress    = $_quote->getBillingAddress(); ?>
<?php $_shippingAddress   = $_quote->getShippingAddress(); ?>
<?php $_pakjeGemakAddress = $this->getPakjeGemakAddress(); ?>
<?php $_paymentOption     = $this->getPaymentOption(); ?>
<div class="order-page">
    <div class="page-title">
        <h1><?php echo $this->__('Checkout Summary'); ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="col2-set">
        <div class="col-1">
            <div class="info-box">
                <h3 class="box-title"><?php echo $this->__('Billing Address'); ?></h3>
                <address class="box-content">
                    <?php echo $_billingAddress->getName(); ?><br />
                    <?php if($_billingAddress->getCompany()): ?>
                        <?php echo $_billingAddress->getCompany(); ?><br />
                    <?php endif; ?>
                    <?php echo $_billingAddress->getStreetFull(); ?><br />
                    <?php echo $_billingAddress->getPostcode(); ?><br />
                    <?php echo $_billingAddress->getCity(); ?><br />
                    <?php if($_billingAddress->getRegion() && $_billingAddress->getRegion() != '-'): ?>
                        <?php echo $_billingAddress->getRegion(); ?><br />
                    <?php endif; ?>      
                    <?php echo $_billingAddress->getCountry(); ?><br /> 
                    <?php if($_billingAddress->getTelephone() && $_billingAddress->getTelephone() != '-'): ?>
                        <?php echo $_billingAddress->getTelephone(); ?><br />
                    <?php endif; ?>
                    <?php echo $_quote->getCustomerEmail(); ?>
                </address>
            </div>
            <div class="info-box">
                <h3 class="box-title"><?php echo $this->__('Shipping Address'); ?></h3>
                <address class="box-content">
                    <?php echo $_shippingAddress->getName(); ?><br />
                    <?php if($_shippingAddress->getCompany()): ?>
                        <?php echo $_shippingAddress->getCompany(); ?><br />
                    <?php endif; ?>
                    <?php echo $_shippingAddress->getStreetFull(); ?><br />
                    <?php echo $_shippingAddress->getPostcode(); ?><br />
                    <?php echo $_shippingAddress->getCity(); ?><br />
                    <?php if($_shippingAddress->getRegion() && $_shippingAddress->getRegion() != '-'): ?>
                        <?php echo $_shippingAddress->getRegion(); ?><br />
                    <?php endif; ?>      
                    <?php echo $_shippingAddress->getCountry(); ?><br /> 
                    <?php if($_shippingAddress->getTelephone() && $_shippingAddress->getTelephone() != '-'): ?>
                        <?php echo $_shippingAddress->getTelephone(); ?><br />
                    <?php endif; ?>
                    <?php echo $_quote->getCustomerEmail(); ?>
                </address>
            </div>
            <?php if($_pakjeGemakAddress): ?>
            <div class="info-box">
                <h3 class="box-title"><?php echo $this->__('Collection Address'); ?></h3>
                <address class="box-content">
                    <?php echo $_pakjeGemakAddress->getName(); ?><br />
                    <?php echo $_pakjeGemakAddress->getStreetFull(); ?><br />
                    <?php echo $_pakjeGemakAddress->getPostcode(); ?><br />
                    <?php echo $_pakjeGemakAddress->getCity(); ?><br />
                    <?php echo $_pakjeGemakAddress->getCountry(); ?>
                </address>
            </div>
            <?php endif; ?>
        </div>
        <div class="col-2">
            <div class="info-box">
                <h3 class="box-title"><?php echo $this->__('Payment Method'); ?></h3>
                <div class="box-content">
                    <p><?php echo $_quote->getPayment()->getMethodInstance()->getTitle(); ?></p>
                    <form name="payment_form" id="payment_form" method="post" action="<?php echo $this->getUrl('postnl/checkout/finishCheckout', array('_secure' => true, 'quote_id' => $_quote->getId())); ?>">
                        <input type="hidden" name="payment[method]" value="<?php echo $_quote->getPayment()->getMethodInstance()->getCode(); ?>"/>
                        <?php if ($this->getChild('payment_method_form')): ?>
                            <?php echo $this->getChildHtml('payment_method_form'); ?>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
            <div class="info-box">
                <h3 class="box-title"><?php echo $this->__('Shipping Method'); ?></h3>
                <div class="box-content">
                    <p><?php echo $this->getShippingDescription(); ?></p>
                    <?php if($_order->getDeliveryDate()): ?>
                        <br/>
                        <p>
                            <?php echo $this->__('Chosen delivery date:'); ?> <strong><?php echo $this->formatDate($_order->getDeliveryDate(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM); ?></strong>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="order-items order-details">
        <h2 class="table-caption"><?php echo $this->__('Items Ordered'); ?></h2>
        <table class="data-table" id="order-summary-table">
            <col>
            <col width="1">
            <col width="1">
            <col width="1">
            <col width="1">
            <thead>
                <th><?php echo $this->__('Product Name'); ?></th>
                <th class="a-right"><?php echo $this->__('Price'); ?></th>
                <th class="a-center"><?php echo $this->__('Qty'); ?></th>
                <th class="a-right"><?php echo $this->__('Subtotal'); ?></th>
            </thead>
            <tbody>
                <?php foreach ($_itemCollection as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </tbody>
            <?php echo $this->getChild('totals')->setQuote($_quote)->toHtml(); ?>
        </table>
    </div>
    
    <div class="buttons-set">
        <p class="back-link">
            <a href="<?php echo $this->getUrl('postnl/checkout/cancel', array('_secure' => true)); ?>" title="<?php echo $this->__('Return to the shopping cart.'); ?>"><?php echo $this->__('Cancel');?></a>
        </p>
        <button class="button" id="postnl_confirm_order" onclick="paymentForm.submit();"><span><span><?php echo $this->__('Confirm Order');?></span></span></button>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
        document.observe('dom:loaded', function() {
            if ($('payment_form_<?php echo $_quote->getPayment()->getMethod(); ?>')) {
                $('payment_form_<?php echo $_quote->getPayment()->getMethod(); ?>').show();
            }
            
            paymentForm = new VarienForm('payment_form');
            
            <?php if ($_paymentOption !== false): ?>
                var paymentOption = $$('option[value="<?php echo $_paymentOption; ?>"]');
                paymentOption.each(function(element) {
                    element.selected = true;
                });
                
                var paymentInput = $$('input[value="<?php echo $_paymentOption; ?>"]');
                paymentInput.each(function(element) {
                    element.checked = true;
                });
            <?php endif; ?>
        });
    //]]>
</script>
