<?php $_helper = $this->helper('postnl'); ?>
<tr>
    <td>
        <h2 class="content-heading"><?php echo $_helper->__('PostNL version');?> <?php echo Mage::getConfig()->getModuleConfig("TIG_PostNL")->version;?></h2>
        <table id="supportWrap" cellpadding="0" cellspacing="0">
            <tr>
                <td class="col-left">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Quick reference guide');?></h3>
                        <ol>
                            <li><strong><?php echo $_helper->__('Lorem ipsum');?> <a target="_blank" href="https://www.postnl.nl/"><?php echo $_helper->__('PostNL');?></a> <?php echo $_helper->__(' dolor sit amet');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('dolore magna aliquam erat volutpat.');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ', Mage::getUrl('*/*/*'));?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Lorem ipsum dolor sit amet');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Lorem ipsum dolor sit amet');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Lorem ipsum dolor sit amet');?></strong>
                                <ol>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                    <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $_helper->__('Lorem ipsum dolor sit amet');?></strong>
                                <ol>
                                   <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                   <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li>
                                   <li><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ');?></li> 
                                </ol>
                            </li>
                        </ol>
                    </div> 
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Legend');?></h3>
                            <ul id="legend">
                                <li class="disabled"><?php echo $_helper->__('PostNL module - Disabled');?></li>
                                <li class="test"><?php echo $_helper->__('PostNL module - Test Modus');?></li>
                                <li class="live"><?php echo $_helper->__('PostNL module - Live Modus');?></li>
                                <li class="advanced"><?php echo $_helper->__('Advanced Configuration');?></li>
                            </ul>
                    </div>
                </td>
                
                <td class="col-faux"></td>
        
                <td class="col-right">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Magento &amp; 3rd party version compatibility');?></h3>
                        <ul>
                            <li><?php echo $_helper->__('Magento Community Edition version');?> 1.5, 1.6, 1.7 &amp; 1.8</li>
                            <li><?php echo $_helper->__('Magento Enterprise Edition version');?> 1.11,1.12 &amp; 1.13</li>
                        </ul>
                        <ul>
                            <li><?php echo $_helper->__('OneStepCheckout version');?> 4.0.7</li>
                        </ul>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Support');?></h3>
                        <p><?php echo $_helper->__('The module is developed by Total Internet Group, commissioned by PostNL. Depending on the nature of the issue or question you should contact either PostNL or Total Internet Group.');?></p>
                        <h4><?php echo $_helper->__('Module basic configuration and account information');?></h4>
                        <p><?php echo $_helper->__('Lorem ipsum dolor sit amet, consectetuer adipiscing elit:');?></p>
                        <p><a href="http://www.postnl.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/logo_postnl.png'); ?>" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $_helper->__('PostNL:');?></td>
                                <td class="last"><a target="_blank" href="https://www.postnl.nl/">www.postnl.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Phone:');?></td>
                                <td class="last">+31(0)20-123-45-67</td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('E-mail:');?></td>
                                <td class="last"><a href="mailto:support@postnl.nl">support@postnl.nl</a></td>
                            </tr>
                        </table>
                        <h4><?php echo $_helper->__('Module support and advanced configuration');?></h4>
                        <p><?php echo $_helper->__('For configuration conflicts, bugs and Magento based support contact Total Internet Group:');?></p>
                        <p><a href="http://www.totalinternetgroup.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/tig_logo_medium.gif'); ?>" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $_helper->__('Online support form:');?></td>
                                <td class="last"><a target="_blank" href="http://support.totalinternetgroup.nl/anonymous_requests/new">support.totalinternetgroup.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('E-mail:');?></td>
                                <td class="last"><a href="mailto:support@totalinternetgroup.nl">support@totalinternetgroup.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Online Documentation');?></td>
                                <td class="last"><a target="_blank" href="http://www.totalinternetgroup.nl/support">www.totalinternetgroup.nl/support</a></td>
                            </tr>
                        </table>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Documentation');?></h3>
                        <p><?php echo $_helper->__('A list of documents regarding the module.');?></p>
                        <ul>
                            <li><a class="pdf" target="_blank" href="<?php echo $this->getSkinUrl('media/TIG/PostNL/manual.pdf')?>" title="<?php echo $_helper->__('Download a PDF format of the manual.');?>"><?php echo $_helper->__('installation manual PostNL module v%s.pdf (NL)', '0.1.0');?></a></li>
                            <li><a target="_blank" href="http://servicedesk.totalinternetgroup.nl/entries/23902302-Release-notes" title="<?php echo $_helper->__('View the complete changelog of the module.');?>"><?php echo $_helper->__('full changelog');?></a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>