<?php
/**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2014 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 5.8
 * @since        Class available since Release 1.0
 */
?>
<div class="billing-address" id="gcheckout-billing-address">
    <h2 class="glc-title"><span class="glc-number">1</span><strong><?php echo $this->__('Billing address');?></strong></h2>
    <div class="glc-col">
        <ul class="form-list">

            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide">
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
            <?php endif; ?>

            <li id="billing-new-address-form">
                <fieldset>
                    <ul>
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('gomage_checkout/onepage_name')->setObject($this->getAddress())->setFieldIdFormat('billing_%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </li>
                        <?php if(!$this->isCustomerLoggedIn()): ?>
                            <li>
                                <label for="billing_email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="billing[email]" id="billing_email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email absolute-advice glc-exists-customer" />
                                </div>
                            </li>
                            <?php if (Mage::helper('gomage_checkout')->getConfigData('address_fields/email_confirmation')): ?>
                                <li>
                                    <label for="billing_email_confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="billing[email_confirmation]" id="billing_email_confirmation" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Confirm Email Address') ?>" class="input-text required-entry validate-email absolute-advice glc-email-confirmation" data-parent-id="billing_email" />
                                    </div>
                                </li>
                            <?php endif ?>
                        <?php endif ?>

                        <?php echo $this->getSortedFields();?>

                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat')->setTemplate('gomage/checkout/html/taxvat.phtml') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <?php

                            $_taxvat->setIsValidVat($this->getAddress()->getIsValidVat());

                            $taxvat_value = '';

                            if ($this->getAddress()->getTaxvat()){
                                $taxvat_value = $this->getAddress()->getTaxvat();
                            } elseif ($this->getAddress()->getVatId()){
                                $taxvat_value = $this->getAddress()->getVatId();
                            } elseif ($this->getQuote()->getCustomerTaxvat()){
                                $taxvat_value = $this->getQuote()->getCustomerTaxvat();
                            }

                            ?>
                            <li>
                                <?php echo $_taxvat->setTaxvat($taxvat_value)->setFieldIdFormat('billing_%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                        <?php endif ?>

                        <?php
                        if(!Mage::helper('gomage_checkout')->getIsAnymoreVersion(1, 4, 0))
                            $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setTemplate('gomage/checkout/html/dob13.phtml');
                        else
                            $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setTemplate('gomage/checkout/html/dob.phtml');
                        ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

                        <?php
                        $_show_dob = !$this->isCustomerLoggedIn() || ($this->isCustomerLoggedIn() && !$this->getQuote()->getCustomerDob()) || Mage::helper('postnl')->quoteIsBirthdayCheck();
                        $_show_gender = !$this->isCustomerLoggedIn() || ($this->isCustomerLoggedIn() && !$this->getQuote()->getCustomerGender());
                        ?>

                        <?php if (($_dob && $_dob->isEnabled() && $_show_dob) ||
                            ($_gender && $_gender->isEnabled() && $_show_gender)): ?>
                            <li class="fields customer-dob <?php if ($_gender && $_gender->isEnabled() && $_show_gender): ?>customer-dob-gender<?php endif;?>">
                                <?php if ($_dob->isEnabled()): ?>
                                    <div class="field">
                                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing_%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($_gender && $_gender->isEnabled() && $_show_gender): ?>
                                    <div class="field">
                                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing_%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif ?>
                            </li>
                        <?php endif ?>

                        <?php if ($_taxvat->isEnabled()): ?>
                            <?php if( in_array(Mage::helper('gomage_checkout')->getConfigData('vat/show_checkbox'), array(1, 2))):?>
                                <li>
                                    <label class="vat-label">
                                        <input id="buy_without_vat" type="checkbox" <?php if($this->getAddress()->getBuyWithoutVat()):?>checked="checked"<?php endif;?> value="1" onclick="$('buy_without_vat_value').value = $('buy_without_vat_value2').value = (this.checked*1);"/>
                                        <span><?php echo Mage::helper('gomage_checkout')->__(Mage::helper('gomage_checkout')->getConfigData('vat/text_under'));?></span>
                                    </label>
                                </li>
                            <?php endif;?>
                            <?php
                            if (Mage::helper('gomage_checkout')->getConfigData('vat/show_checkbox')==3){
                                $without_vat_value = 1;
                            }else{
                                if($this->getAddress()->getBuyWithoutVat()){
                                    $without_vat_value = 1;
                                }else{
                                    $without_vat_value = 0;
                                }
                            }
                            ?>
                            <input id="buy_without_vat_value" type="hidden" value="<?php echo $without_vat_value; ?>" name="billing[buy_without_vat]"/>
                            <input id="buy_without_vat_value2" type="hidden" value="<?php echo $without_vat_value; ?>" name="shipping[buy_without_vat]"/>
                        <?php endif; ?>


                        <?php if(!$this->isCustomerLoggedIn() && !$this->getAutoRegistration()): ?>
                            <?php if(!$this->isCustomerLoggedIn() && in_array($this->getCheckoutMode(), array(0, 1))):?>
                                <?php if($this->getCheckoutMode() == 0):?>
                                    <li class="control control-register">
                                        <input class="radio" id="customer_account_create" onclick="if(this.checked){$('register-customer-password').style.display='block';}else{$('register-customer-password').style.display='none';}" type="checkbox" <?php if(Mage::getSingleton('customer/session')->getCreateAccount()):?>checked="checked"<?php endif;?> name="create_account" value="1"  />
                                        <label for="customer_account_create"><?php echo $this->__('Create an Account');?></label>
                                    </li>
                                <?php endif;?>
                                <li class="fields" id="register-customer-password" <?php if(!Mage::getSingleton('customer/session')->getCreateAccount() && $this->getCheckoutMode() == 0):?>style="display:none;"<?php endif;?>>
                                    <div class="field">
                                        <label for="billing_customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[customer_password]" id="billing_customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                        </div>
                                    </div>
                                    <div class="field">
                                        <label for="billing_confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing_confirm_password" class="input-text validate-cpassword" />
                                        </div>
                                    </div>
                                    <?php if ($this->isReferralBlockShow()): ?>
                                        <div class="input-box">
                                            <label for="rewards_referral"><?php echo $this->getReferralLabel() ?></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->getReferralLabel() ?>" class="input-text" id="rewards_referral" name="billing[rewards_referral]" />
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </li>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </fieldset>
            </li>
            <?php if ($this->isCustomerLoggedIn()):?>
                <li id="billing_address_book" class="control control-siab" style="display:none">
                    <input type="checkbox" name="billing[save_in_address_book]" id="billing_save_in_address_book" value="1" title="<?php echo  $this->__('Save in address book') ?>" class="checkbox" />
                    <label for="billing_save_in_address_book"><?php echo  $this->__('Save in address book') ?></label>
                </li>
            <?php endif; ?>
            <?php if ($this->canShip()):?>
                <li class="control control-stta">
                    <input type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" <?php if($this->shippingAsBilling()):?> checked="checked" <?php endif;?> title="<?php echo  $this->__('Ship to this address') ?>" onclick="checkout.changeAddressMode(this.checked)" class="radio" />
                    <label for="billing_use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
                </li>
            <?php endif; ?>
            <?php if ($this->helper('postnl/deliveryOptions')->quoteIsIDCheck()): ?>
            <li>
                <?php echo $this->getChildHtml('postnl_billing_idcheck'); ?>
            </li>
            <?php endif; ?>
        </ul>
        <?php if (!$this->canShip()): ?>
            <input type="hidden" name="billing[use_for_shipping]" value="1" />
        <?php endif; ?>
    </div>
</div>