<?php
/**
 *                  ___________       __            __   
 *                  \__    ___/____ _/  |_ _____   |  |  
 *                    |    |  /  _ \\   __\\__  \  |  |
 *                    |    | |  |_| ||  |   / __ \_|  |__
 *                    |____|  \____/ |__|  (____  /|____/
 *                                              \/       
 *          ___          __                                   __   
 *         |   |  ____ _/  |_   ____ _______   ____    ____ _/  |_ 
 *         |   | /    \\   __\_/ __ \\_  __ \ /    \ _/ __ \\   __\
 *         |   ||   |  \|  |  \  ___/ |  | \/|   |  \\  ___/ |  |  
 *         |___||___|  /|__|   \_____>|__|   |___|  / \_____>|__|  
 *                  \/                           \/               
 *                  ________       
 *                 /  _____/_______   ____   __ __ ______  
 *                /   \  ___\_  __ \ /  _ \ |  |  \\____ \ 
 *                \    \_\  \|  | \/|  |_| ||  |  /|  |_| |
 *                 \______  /|__|    \____/ |____/ |   __/ 
 *                        \/                       |__|    
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL: 
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@totalinternetgroup.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@totalinternetgroup.nl for more information.
 *
 * @copyright   Copyright (c) 2013 Total Internet Group B.V. (http://www.totalinternetgroup.nl)
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */
?>

<?php if (!Mage::helper('postnl')->isEnabled()): ?>
    <?php return $this; ?>
<?php endif; ?>

<?php $_shipment = Mage::registry('current_shipment'); ?>
<?php if ($_shipment->getOrder()->getShippingMethod() != 'postnl_postnl'): ?>
    <?php return $this; ?>
<?php endif; ?>

<?php $_productOptions = Mage::helper('postnl/cif')->getProductOptionsForShipment($_shipment); ?>
<script type ="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function() {
        postnlProductOptionsContainer = new Element('p');
        
        postnlProductOptionsLabel = new Element('label', {
            'class': 'normal',
            'for'  : 'postnl_product_option'
        });
        postnlProductOptionsLabel.update('PostNL Shipping Options');
        
        postnlProductOption = new Element('select', {
           'name' : 'postnl[product_option]',
           'class': 'select required-entry',
           'id'   : 'postnl_product_option'
        });
        
        
        <?php foreach($_productOptions as $_option): ?>
            option = new Element('option', {
                <?php if (isset($_option['isExtraCover']) && $_option['isExtraCover'] === true): ?>
                    'class': 'extra_cover',
                <?php endif; ?>
                'value': '<?php echo $_option['value']; ?>'
            });
            option.update('<?php echo $_option['label']; ?>');
            
            postnlProductOption.insert(option);
        <?php endforeach; ?>
        
        postnlProductOptionsContainer.insert(postnlProductOptionsLabel);
        postnlProductOptionsContainer.insert(postnlProductOption);
        $$('.order-totals-bottom div.a-right').each(function(element) {
            element.insert({
                before: postnlProductOptionsContainer
            });
        });
        
        postnlExtraCoverContainer = new Element('p', {
            'id'   : 'postnl_extra_cover_container',
            'style': 'display:none;'
        });
        postnlExtraCoverLabel = new Element('label', {
            'class': 'normal',
            'for'  : 'postnl_extra_cover'
        });
        postnlExtraCoverLabel.update('Extra cover amount');
        
        postnlExtraCoverField = new Element('input', {
            'type' : 'text',
            'name' : 'postnl[extra_cover_amount]',
            'class': 'input-text required-entry',
            'id'   : 'postnl_extra_cover_value',
            'value': '<?php echo number_format($_shipment->getOrder()->getBaseGrandTotal(), 2); ?>',
        });
        
        postnlExtraCoverContainer.insert(postnlExtraCoverLabel);
        postnlExtraCoverContainer.insert(postnlExtraCoverField);
        
        $('postnl_product_option').insert({
            after: postnlExtraCoverContainer
        });
        
        var productOptions = $('postnl_product_option');
        productOptions.observe('change', function() {
            if (productOptions[productOptions.selectedIndex].hasClassName('extra_cover')) {
                $('postnl_extra_cover_container').show();
            } else {
                $('postnl_extra_cover_container').hide();
            }
        });
        
        if (productOptions[productOptions.selectedIndex].hasClassName('extra_cover')) {
            $('postnl_extra_cover_container').show();
        } else {
            $('postnl_extra_cover_container').hide();
        }
    });
//]]>
</script>
