<?php 
 /**
 *                  ___________       __            __   
 *                  \__    ___/____ _/  |_ _____   |  |  
 *                    |    |  /  _ \\   __\\__  \  |  |
 *                    |    | |  |_| ||  |   / __ \_|  |__
 *                    |____|  \____/ |__|  (____  /|____/
 *                                              \/       
 *          ___          __                                   __   
 *         |   |  ____ _/  |_   ____ _______   ____    ____ _/  |_ 
 *         |   | /    \\   __\_/ __ \\_  __ \ /    \ _/ __ \\   __\
 *         |   ||   |  \|  |  \  ___/ |  | \/|   |  \\  ___/ |  |  
 *         |___||___|  /|__|   \_____>|__|   |___|  / \_____>|__|  
 *                  \/                           \/               
 *                  ________       
 *                 /  _____/_______   ____   __ __ ______  
 *                /   \  ___\_  __ \ /  _ \ |  |  \\____ \ 
 *                \    \_\  \|  | \/|  |_| ||  |  /|  |_| |
 *                 \______  /|__|    \____/ |____/ |   __/ 
 *                        \/                       |__|    
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL: 
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@totalinternetgroup.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@totalinternetgroup.nl for more information.
 *
 * @copyright   Copyright (c) 2013 Total Internet Group B.V. (http://www.totalinternetgroup.nl)
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */
?>
<?php $_version = (string) Mage::getConfig()->getModuleConfig("TIG_PostNL")->version; ?>
<tr>
    <td>
        <h2 class="content-heading"><img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/logo_postnl.png'); ?>"/> <?php echo $this->__('PostNL version %s', $_version);?></h2>
        <table id="supportWrap" cellpadding="0" cellspacing="0">
            <tr>
                <td colspan="3">
                    <div class="text-box">
                        <h4><?php echo $this->__("We highly reccommend you place several 'test'  shipments, before you use the extension for real orders and real shipments."); ?></h4>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <div class="text-box">
                        <h4><?php echo $this->__('Before you proceed to use this extension it is very important that you have properly configured certain elements of your Magento webshop.'); ?></h4>
                        <ul class="postnl-config-warning">
                            <li><?php echo $this->__("You should make sure that each product you intend to ship using PostNL has a correct value for it's weight attribute. You can select a unit of measurement for this attribute in the 'Confirming & Label Settings' tab below. If you do not do this, PostNL may charge you extra when a parcel turns out to weigh significantly more than expected or they may even refuse your shipment."); ?></li>
                            <li><?php echo $this->__("Make sure the PostNL shipping method is configured under system > config > shipping methods > PostNL. Only shipments made using this shipping method will be able to use PostNL's services. You may choose to charge either a flat rate or a table rate-based shipping fee. In the case of the latter, the table rates you have added under the Table Rate shipping method will be used. More info on how to setup the Table Rate shipping method can be found <a href='%s' target='_blank'>here</a>.", 'http://www.magentocommerce.com/knowledge-base/entry/how-do-i-set-up-table-rate-shipping'); ?></li>
                            <li><?php echo $this->__("You should properly configure your checkout process. PostNL needs to be able to retrieve a properly formatted address from the checkout process in order to guarantee the order is delivered at the correct address. In order to do so, you need to enable the appropriate number of street lines in your checkout flow and make sure these have correct labels and validation settings. More info on how to do this, can be found <a href='%s' target='_blank'>here</a>.", 'http://kb.totalinternetgroup.nl/topic/31080848'); ?></li>
                        </ul>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="col-left">
                    <div class="text-box">
                        <h3><?php echo $this->__('Quick reference guide');?></h3>
                        <ol>
                            <li><strong><?php echo $this->__('Register the extension for use');?></strong>
                                <ol>
                                    <li><?php echo $this->__("Open the 'General Settings' tab and enter your email address.");?></li>
                                    <li><?php echo $this->__("Press the 'Activate the extension' button. You will now recieve an email at the address you specified containing 2 secure keys.");?></li>
                                    <li><?php echo $this->__("Copy the keys and enter them in the 'Unique-' and 'Private key' fields that are now available.");?></li>
                                    <li><?php echo $this->__("Press the 'Finish activation' button.");?></li>
                                    <li><?php echo $this->__("Set the 'Active' field to 'Yes' and save the configuration. Your extension is now registered.");?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $this->__('Configure your PostNL account');?></strong>
                                <ol>
                                    <li><?php echo $this->__("Make sure you have your PostNL account info with you. You will need the following info: username & password, customer number, customer code, and BLS code. You need to enter these in the 'Account Settings' tab.");?></li>
                                    <li><?php echo $this->__("First enter your username and password. Depending on the status of your account, you may either enter the 'test' or 'live' version of these fields. Please note: if you do not enter the 'live' fields, you will only be able to create test shipments.");?></li>
                                    <li><?php echo $this->__('Next enter your customer number, customer code and BLS code. If you are unsure about which information to enter here, please contact PostNL.'); ?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $this->__('Enter a sender and return address');?></strong>
                                <ol>
                                    <li><?php echo $this->__('You have to enter the address to which PostNL may return shipments that could not be delivered. The sender address is mandatory. You may also enter a separate, optional return address.');?></li>
                                    <li><?php echo $this->__("Go to the 'Sender Address' tab and enter your address. If you enter a company name, it will be printed on the shipping label. Otherwise, your name will be printed.");?></li>
                                    <li><?php echo $this->__('You may now choose to enter a separate return address. If you choose to do so, this address will be printed on the shipping labels, rather than your sender address.');?></li>
                                    <li><?php echo $this->__("In order to enter a separare return address, go to the 'Return Address' tab and switch the 'Use the sender address as the return adress' settng to 'no'. New fields will now appear for you to enter your return address."); ?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $this->__('Configure your address settings, your confirming & label printing preferences and your preferred product options');?></strong>
                                <ol>
                                    <li><?php echo $this->__("Go to the 'Address Settings' tab and configure this section based on which fields you use in your checkout process. If this does not precisely match your checkout process, orders may not be shipped to the correct address.");?></li>
                                    <li><?php echo $this->__("Go to the 'Confirming & Label Printing Settings' tab and change your preferences. You may want to tweak these and then test them repeatedly before deciding on a final configuration.");?></li>
                                    <li><?php echo $this->__("Go to the 'Product Options' tab and select your supported and preferred product options. If you have questions regarding each product option and which would be most suitable to you, please contact PostNL.");?></li>
                                </ol>
                            </li>
                            <li><strong><?php echo $this->__('Configure your GlobalPack settings');?></strong>
                                <ol>
                                   <li><?php echo $this->__('If you wish to send orders to outside the EU, you need to configure your GlobalPack settings.');?></li>
                                   <li><?php echo $this->__("Go to the 'Account Settings' tab and fill in the 'Global Barcode Type' and 'Global Barcode Range' fields.");?></li>
                                   <li><?php echo $this->__("Go to the 'GlobalPack Settings' tab and specify your preferences. Be aware, that if you do not configure these settings correctly, international shipments may be refused by either PostNL or the customs office.");?></li> 
                                </ol>
                            </li>
                            <li><strong><?php echo $this->__('Configure your PostNL Checkout settings');?></strong>
                                <ol>
                                   <li><?php echo $this->__('If you wish to use PostNL Checkout in your webshop, you need to configure your PostNl Checkout settings.');?></li>
                                   <li><?php echo $this->__("Go to the 'Account Settings' tab and fill in the 'Webshop ID' and 'Public Webshop ID' fields.");?></li>
                                   <li><?php echo $this->__("Go to the 'PostNL Checkout' tab and specify your preferences.");?></li> 
                                   <li><?php echo $this->__("Go to the 'PostNL Checkout Paymen Settings' tab and specify which payment methods PostNL Checkout supports. Here you must also link the PostNL Checkout payment methods to the payment methods you use in Magento. If you do not configure this properly, customers may be forced to pay with a different payment method than the one they selected.");?></li> 
                                </ol>
                            </li>
                        </ol>
                    </div>
                </td>
                
                <td class="col-faux"></td>
        
                <td class="col-right">
                    <div class="text-box">
                        <h3><?php echo $this->__('Magento &amp; 3rd party version compatibility');?></h3>
                        <ul>
                            <li><?php echo $this->__('Magento Community Edition version');?> v1.6, v1.7 &amp; v1.8</li>
                            <li><?php echo $this->__('Magento Enterprise Edition version');?> v1.11, v1.12 &amp; v1.13</li>
                        </ul>
                        <ul>
                            <li><?php echo $this->__('OneStepCheckout version');?> v4.x</li>
                        </ul>
                        <ul>
                            <li><?php echo $this->__('If you wish to use this extension on an unsupported Magento version or edition, or in combination with an unsupported 3rd party extension, we cannot guarantee the PostNL extension will function as expected. For questions please contact the Total Internet Group servicedesk.'); ?></li>
                        </ul>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $this->__('Support');?></h3>
                        <p><?php echo $this->__('The extension is developed by Total Internet Group, commissioned by PostNL. Depending on the nature of the issue or question you should contact either PostNL or Total Internet Group.');?></p>
                        <h4><?php echo $this->__('PostNL account information and PostNL services');?></h4>
                        <p><?php echo $this->__('For questions related to your PostNL account and PostNL delivery options, please contact PostNL.');?></p>
                        <p><a href="http://www.postnl.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/logo_postnl.png'); ?>" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $this->__('PostNL:');?></td>
                                <td class="last"><a target="_blank" href="http://www.postnl.nl/zakelijk/e-commerce/flexibele-bezorgopties">http://www.postnl.nl/zakelijk/e-commerce/flexibele-bezorgopties</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $this->__('Phone:');?></td>
                                <td class="last">058-2333343</td>
                            </tr>
                        </table>
                        <h4><?php echo $this->__('Extension support and configuration questions');?></h4>
                        <p><?php echo $this->__('For configuration problems, extension conflicts and bugs, contact Total Internet Group.');?></p>
                        <p><a href="http://www.totalinternetgroup.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/TIG/PostNL/tig_logo_medium.gif'); ?>" alt="" /></a></p>
                        <table class="contact">
                             <tr>
                                <td class="first"><?php echo $this->__('Online knowledgebase:');?></td>
                                <td class="last"><a target="_blank" href="http://servicedesk.totalinternetgroup.nl/forums">http://servicedesk.totalinternetgroup.nl/forums</a></td>
                            </tr>
                             <tr>
                                <td class="first"><?php echo $this->__('Request help directly:');?></td>
                                <td class="last"><a target="_blank" href="http://servicedesk.totalinternetgroup.nl/requests/new">http://servicedesk.totalinternetgroup.nl/requests/new</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $this->__('Email:');?></td>
                                <td class="last"><a href="mailto:servicedesk@totalinternetgroup.nl">servicedesk@totalinternetgroup.nl</a></td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $this->__('Phone:');?></td>
                                <td class="last">+31(0)20 – 21 81 001</td>
                            </tr>
                        </table>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $this->__('Documentation');?></h3>
                        <p><?php echo $this->__('A list of documents regarding the extension.');?></p>
                        <ul>
                            <li><a class="pdf" target="_blank" href="<?php echo $this->getSkinUrl('media/TIG/PostNL/manual.pdf')?>" title="<?php echo $this->__('View the installation and configuration manual.');?>"><?php echo $this->__('Installation and configuration manual');?></a></li>
                            <li><a target="_blank" href="http://servicedesk.totalinternetgroup.nl/entries/38584893" title="<?php echo $this->__('View the complete changelog of the extension.');?>"><?php echo $this->__('Full changelog');?></a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>