<?php
/**
 *                  ___________       __            __   
 *                  \__    ___/____ _/  |_ _____   |  |  
 *                    |    |  /  _ \\   __\\__  \  |  |
 *                    |    | |  |_| ||  |   / __ \_|  |__
 *                    |____|  \____/ |__|  (____  /|____/
 *                                              \/       
 *          ___          __                                   __   
 *         |   |  ____ _/  |_   ____ _______   ____    ____ _/  |_ 
 *         |   | /    \\   __\_/ __ \\_  __ \ /    \ _/ __ \\   __\
 *         |   ||   |  \|  |  \  ___/ |  | \/|   |  \\  ___/ |  |  
 *         |___||___|  /|__|   \_____>|__|   |___|  / \_____>|__|  
 *                  \/                           \/               
 *                  ________       
 *                 /  _____/_______   ____   __ __ ______  
 *                /   \  ___\_  __ \ /  _ \ |  |  \\____ \ 
 *                \    \_\  \|  | \/|  |_| ||  |  /|  |_| |
 *                 \______  /|__|    \____/ |____/ |   __/ 
 *                        \/                       |__|    
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License.
 * It is available through the world-wide-web at this URL: 
 * http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to servicedesk@totalinternetgroup.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact servicedesk@totalinternetgroup.nl for more information.
 *
 * @copyright   Copyright (c) 2013 Total Internet Group B.V. (http://www.totalinternetgroup.nl)
 * @license     http://creativecommons.org/licenses/by-nc-nd/3.0/nl/deed.en_US
 */
?>
<?php foreach (Mage::registry('current_order')->getShipmentsCollection() as $_shipment): ?>
    <?php $_progressStatus = $this->getShippingStatus($_shipment) ?>

    <div id="postnl_status_bar-<?php echo $_shipment->getId(); ?>" class="progress-wrapper <?php echo $progressStatus ?>">
        <div class="progress progress-reported">
            <strong><?php echo $this->__('Confirmed') ?></strong>
        </div>
        
        <div class="progress progress-distribution">
            <strong><?php echo $this->__('Distribution Center') ?></strong>
        </div>
        
        <div class="progress progress-transit">
            <strong><?php echo $this->__('In Transit') ?></strong>
        </div>
        
        <div class="progress progress-delivered">
            <strong><?php echo $this->__('Delivered') ?></strong>
        </div>
    </div>
    
    <script type="text/javascript">
    //<![CDATA[
        document.observe('dom:loaded', function() {
            statusBar<?php echo $_shipment->getId(); ?> = $('postnl_status_bar-<?php echo $_shipment->getId(); ?>');
            if ($('my-tracking-table-<?php echo $_shipment->getId(); ?>')) {
                $('my-tracking-table-<?php echo $_shipment->getId(); ?>').insert({
                    before: statusBar<?php echo $_shipment->getId(); ?>
                });
            } else {
                $('my-shipment-table-<?php echo $_shipment->getId(); ?>').previous().insert({
                    before: statusBar<?php echo $_shipment->getId(); ?>
                });
            }
        });
    //]]>
    </script>
<?php endforeach; ?>
